# Generated by Django 4.1.7 on 2023-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desceiption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='modefield_date',
            new_name='modified_date',
        ),
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
